isics_open_miam_miam_user:
    resource: "@IsicsOpenMiamMiamUserBundle/Resources/config/routing.yml"

isics_open_miam_miam_admin:
    resource: "@IsicsOpenMiamMiamBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

isics_open_miam_miam_main:
    resource: "@IsicsOpenMiamMiamBundle/Resources/config/routing/main.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
