<?php

namespace Isics\Bundle\OpenMiamMiamBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTypeRepository extends EntityRepository
{
}
